name: flutter_nfc_acs2
description: A plugin for communicating with the ACR1255U-J1 BT reader from Advanced Card Systems Ltd using SPM and modern native APIs.
version: 0.3.0
homepage: https://github.com/hidayatulrohani94/flutter_nfc_acs

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.24

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.vnet.flutter_nfc_acs
        pluginClass: FlutterNfcAcsPlugin
      ios:
        pluginClass: FlutterNfcAcsPlugin
